name: Node CI

on:
  push:
    branches: master
    paths-ignore:
      - "docs/**"
      
  pull_request:
    branches: master
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Install 🔧
        run: npm install

      - name: Lint 🧐
        run: npm run lint:check

      - name: Test 🚨
        run: npm test

      - name: Build 🏗️
        run: npm run build
